<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;


/**
 * InfoEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEquipoRepository extends EntityRepository
{
    public function getArrayEquipoHistorial($equipoId)
    {
        $objResultSetMap = new ResultSetMappingBuilder($this->_em);
        $objNativeQuery = $this->_em->createNativeQuery(null, $objResultSetMap);
        
        $strSql = "select CONVERT(observacion USING utf8) OBSERVACION,
                    USR_CREACION, FE_CREACION FROM
                    INFO_EQUIPO_HISTORIAL WHERE EQUIPO_ID = :equipo";
        
        $objResultSetMap->addScalarResult('OBSERVACION', 'observacion','string');
        $objResultSetMap->addScalarResult('USR_CREACION','usrCreacion','string');
        $objResultSetMap->addScalarResult('FE_CREACION', 'feCreacion','string');
        
        $objNativeQuery->setParameter("equipo", $equipoId);
        
        $objNativeQuery->setSQL($strSql);

        $arrayCapacidades = $objNativeQuery->getArrayResult();
        
        return $arrayCapacidades;
    }
}
