<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;


/**
 * InfoScriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoScriptRepository extends EntityRepository
{
    public function getArrayScripts($idScript)
    {
        $objResultSetMap = new ResultSetMappingBuilder($this->_em);
        $objNativeQuery = $this->_em->createNativeQuery(null, $objResultSetMap);
        $boolArray = true;
        
        $strWhere = "";
        
        if($idScript != '')
        {
            $strWhere = " and id_script = :script ";
            $objNativeQuery->setParameter("script", $idScript);
            $boolArray = false;
        }
        
        $strSql = "select ID_SCRIPT, CONVERT(script USING utf8) SCRIPT,
                    NOMBRE_SCRIPT, DESCRIPCION, FE_CREACION, ESTADO , USR_CREACION FROM
                    INFO_SCRIPT where estado <> 'Eliminado' $strWhere ";                
        
        $objResultSetMap->addScalarResult('ID_SCRIPT', 'idScript','string');
        $objResultSetMap->addScalarResult('SCRIPT', 'script','string');
        $objResultSetMap->addScalarResult('NOMBRE_SCRIPT', 'nombreScript','string');
        $objResultSetMap->addScalarResult('DESCRIPCION', 'descripcion','string');
        $objResultSetMap->addScalarResult('ESTADO', 'estado','string');
        $objResultSetMap->addScalarResult('USR_CREACION','usrCreacion','string');
        $objResultSetMap->addScalarResult('FE_CREACION', 'feCreacion','string');                
        
        $objNativeQuery->setSQL($strSql);

        $arrayCapacidades = $boolArray?
                $objNativeQuery->getArrayResult():$objNativeQuery->getOneOrNullResult();
        
        return $arrayCapacidades;
    }
}
